CREATE TABLE IF NOT EXISTS Players (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS Matches (
    ID SERIAL PRIMARY KEY,
    Player1 INTEGER NOT NULL REFERENCES Players(ID) ON DELETE CASCADE,
    Player2 INTEGER NOT NULL REFERENCES Players(ID) ON DELETE CASCADE,
    Winner INTEGER NOT NULL REFERENCES Players(ID) ON DELETE CASCADE,
    Score VARCHAR(50) NOT NULL
    );